services:
  app:
    build:
      args:
        user: john
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: finance-tracker
    container_name: ft-backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: app
    working_dir: /var/www/backend/
    volumes:
      - ./:/var/www/backend
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ft-network

  db:
    image: mysql:8.4
    container_name: ft-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      # - ./docker-compose/mysql:/var/lib/mysql # seems to not work
    networks:
      - ft-network

  nginx:
    image: nginx:1.28-alpine
    container_name: ft-nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./:/var/www/backend
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - ft-network

networks:
  ft-network:
    driver: bridge
